# Generated by Django 4.1 on 2022-08-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bill')),
            ],
        ),
    ]
