# Generated by Django 4.1 on 2022-08-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bill')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
