# Generated by Django 4.1 on 2022-08-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_billowner_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billowner',
            name='bills',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.billowner'),
            preserve_default=False,
        ),
    ]
