# Generated by Django 4.1 on 2022-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_bill_name_remove_billowner_bills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(default='Untitled Bill', max_length=100),
        ),
    ]
