# Generated by Django 4.1 on 2022-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_billowner_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_link',
            field=models.CharField(default='Link not provided', max_length=100),
        ),
    ]
